/**
 * The tokenized stocks Trador treats as real.
 *
 * This list is the trust boundary of the whole app. A coin earns its place in
 * the feed by being paired against something in here, so a wrong entry becomes
 * a laundering route: mint a token called OPENAI, pair a coin to it, and the
 * coin inherits a real asset's credibility.
 *
 * So membership is not "the ticker looks right" and not "a token list said so".
 * Every entry is generated by `npm run sync:stocks`, which censuses real
 * StonkFun pools, groups the quote assets by **mint authority**, and emits only
 * the families whose authority is recognised. Two findings from that census are
 * why the authority is the test rather than a name or an address prefix:
 *
 *   - `xSOL` ("Hylo Leveraged SOL") is quoted against by 718 launches and would
 *     pass any prefix rule aimed at xStocks. It is a leveraged SOL derivative.
 *   - `tOpenAI` sits in the census beside PreStocks' `OPENAI` under a different
 *     authority — two tokens offering OpenAI exposure, one issuer verified and
 *     one not. Names cannot separate them. Authorities can, instantly.
 *
 * The registry is deliberately small and correct rather than large and
 * plausible. An unrecognised quote mint makes a coin fail the universe test,
 * which under-includes: a coin that belongs in the feed is missing, and someone
 * notices. The opposite mistake mis-attributes, which nobody can see. So
 * absence from this file means "not yet verified", never "not real".
 */

import {type Pubkey, assertPubkey, samePubkey} from "@/lib/pubkey";

import GENERATED from "./mints.generated.json" with {type: "json"};

export type StockIssuer = "backed" | "prestocks" | "backpack";
export type StockKind = "equity" | "etf" | "pre-ipo" | "commodity";

/**
 * Where an authoritative price can come from.
 *
 * `pyth` — a real oracle feed exists for the underlying.
 * `none` — the company is not publicly listed, so no oracle and no exchange
 *          quote exists. The only number available is what a pool says, and the
 *          UI has to admit that rather than present it as a quote.
 */
export type PriceAuthority = "pyth" | "none";

export interface StockMint {
  readonly ticker: string;
  readonly name: string;
  readonly mint: Pubkey;
  readonly decimals: number;
  /**
   * The SPL program that owns the mint, read off the account — never assumed.
   * Every stock verified so far is Token-2022, and deriving an associated token
   * address against the classic program instead returns a different,
   * valid-looking address that silently sends value nowhere.
   */
  readonly tokenProgram: Pubkey;
  readonly issuer: StockIssuer;
  readonly kind: StockKind;
  readonly priceAuthority: PriceAuthority;
  /** How many StonkFun launches were priced against this mint at sync time. */
  readonly launchesQuotedAgainst: number;
  readonly verified: {
    readonly mintAuthority: Pubkey | null;
    readonly at: string;
    readonly source: string;
  };
}

export const ISSUERS: Record<StockIssuer, {label: string; verification: "issuer-key" | "per-mint"}> =
  {
    backed: {label: "xStocks", verification: "issuer-key"},
    prestocks: {label: "PreStocks", verification: "issuer-key"},
    // Backpack mints each carry their own authority, so there is no single key
    // that proves the family — membership is a maintained allowlist, which is a
    // weaker guarantee. Disabled unless `sync:stocks` was run with
    // INCLUDE_BACKPACK=1.
    backpack: {label: "Backpack Securities", verification: "per-mint"},
  };

const KNOWN_ISSUERS = new Set(Object.keys(ISSUERS));
const KNOWN_KINDS = new Set<StockKind>(["equity", "etf", "pre-ipo", "commodity"]);

/**
 * Validate at module load.
 *
 * The generated file is reviewed in a diff, but a diff is a person and people
 * skim. An entry missing its authority, or carrying a mint that is not base58,
 * should fail the process at boot rather than quietly become a row that lets a
 * coin claim a stock pairing. This is the one place where throwing on import is
 * the right trade.
 */
function load(): readonly StockMint[] {
  const seenMints = new Set<string>();
  const seenTickers = new Set<string>();

  return (GENERATED as unknown[]).map((raw, index) => {
    const entry = raw as Record<string, unknown>;
    const where = `mints.generated.json[${index}]`;

    const mint = assertPubkey(entry.mint, `${where}.mint`);
    const tokenProgram = assertPubkey(entry.tokenProgram, `${where}.tokenProgram`);
    const ticker = String(entry.ticker ?? "");
    const issuer = String(entry.issuer ?? "");
    const kind = String(entry.kind ?? "") as StockKind;

    if (!ticker) throw new Error(`${where}: missing ticker`);
    if (!KNOWN_ISSUERS.has(issuer)) throw new Error(`${where}: unknown issuer "${issuer}"`);
    if (!KNOWN_KINDS.has(kind)) throw new Error(`${where}: unknown kind "${kind}"`);

    const verified = entry.verified as {mintAuthority?: unknown; at?: unknown; source?: unknown} | undefined;
    if (!verified?.mintAuthority) {
      throw new Error(
        `${where} (${ticker}): no verified mint authority. Entries without one ` +
          `must not ship — rerun npm run sync:stocks.`,
      );
    }

    if (seenMints.has(mint)) throw new Error(`${where}: duplicate mint ${mint}`);
    if (seenTickers.has(ticker)) throw new Error(`${where}: duplicate ticker ${ticker}`);
    seenMints.add(mint);
    seenTickers.add(ticker);

    const decimals = Number(entry.decimals);
    if (!Number.isInteger(decimals) || decimals < 0 || decimals > 18) {
      throw new Error(`${where} (${ticker}): implausible decimals ${String(entry.decimals)}`);
    }

    return {
      ticker,
      name: String(entry.name ?? ticker),
      mint,
      decimals,
      tokenProgram,
      issuer: issuer as StockIssuer,
      kind,
      // A pre-IPO name has no public market, so nothing can be authoritative
      // about its price regardless of what the generated file claims.
      priceAuthority: kind === "pre-ipo" ? "none" : ((entry.priceAuthority as PriceAuthority) ?? "pyth"),
      launchesQuotedAgainst: Number(entry.launchesQuotedAgainst ?? 0),
      verified: {
        mintAuthority: assertPubkey(verified.mintAuthority, `${where}.verified.mintAuthority`),
        at: String(verified.at ?? ""),
        source: String(verified.source ?? ""),
      },
    } satisfies StockMint;
  });
}

export const STOCK_MINTS: readonly StockMint[] = load();

const BY_MINT: ReadonlyMap<string, StockMint> = new Map(
  STOCK_MINTS.map((stock) => [stock.mint, stock]),
);

const BY_TICKER: ReadonlyMap<string, StockMint> = new Map(
  STOCK_MINTS.map((stock) => [stock.ticker.toUpperCase(), stock]), // pubkey-lint-ok: ticker, not a mint
);

export function stockForMint(value: string): StockMint | null {
  return BY_MINT.get(value) ?? null;
}

/** Tickers are labels, so folding their case is correct — unlike a mint. */
export function stockForTicker(ticker: string): StockMint | null {
  return BY_TICKER.get(ticker.toUpperCase()) ?? null; // pubkey-lint-ok: ticker, not a mint
}

export function isStockMint(value: string): boolean {
  return BY_MINT.has(value);
}

/**
 * The tokenized stock in a pair, if either side is one.
 *
 * Checks the quote side first. Both sides being stocks is possible in principle
 * and is not something to silently pick a winner for, so the caller gets the
 * quote side — the thing the coin is priced in.
 */
export function stockSideOf(mintA: string, mintB: string): StockMint | null {
  return stockForMint(mintB) ?? stockForMint(mintA);
}

export function sameStock(a: StockMint, b: StockMint): boolean {
  return samePubkey(a.mint, b.mint);
}

export function stocksByIssuer(issuer: StockIssuer): StockMint[] {
  return STOCK_MINTS.filter((stock) => stock.issuer === issuer);
}

/** Entries an oracle can price. Everything else is pool-priced and says so. */
export function oraclePricedStocks(): StockMint[] {
  return STOCK_MINTS.filter((stock) => stock.priceAuthority === "pyth");
}

/** Ranked by how much of the launch population actually prices against them. */
export function stocksByPopularity(): StockMint[] {
  return [...STOCK_MINTS].sort(
    (a, b) => b.launchesQuotedAgainst - a.launchesQuotedAgainst,
  );
}
